### ISSUE TITLE
ISBN

### ISSUE THREAD

**Issue by rcfroggatt786** [ibm-developer-skills-network/rpszc-nodejsFinalModule#87]
There don't appear to be ISBNs in the book database, making the final project problematic.

**Comment by TheCmunkey** [comment]
Just use the dictionary keys. LOL

**Comment by TheCmunkey** [comment]
> There don't appear to be ISBNs in the book database, making the final project problematic.

Just use the dictionary keys. LOL

**Comment by rcfroggatt786** [comment]
Yes, that's an option. Wasn't sure if that was the intent or not as they don't look like ISBNs. In the end I just added new key-value pairs for ISBN.

**Comment by TheCmunkey** [comment]
> Yes, that's an option. Wasn't sure if that was the intent or not as they don't look like ISBNs. In the end I just added new key-value pairs for ISBN.

I considered that as well, but it doesn't look like their sample output. No worries.
